--<ScriptOptions statementTerminator=";"/>

CREATE TABLE COMPANY (
		ID VARCHAR(36) NOT NULL,
		CREATEDBY VARCHAR(50) NOT NULL,
		CREATEDDATE TIMESTAMP NOT NULL,
		LASTMODIFIEDBY VARCHAR(50) NOT NULL,
		LASTMODIFIEDDATE TIMESTAMP NOT NULL,
		LOWERNAME VARCHAR(50),
		NAME VARCHAR(50) NOT NULL
	);

CREATE UNIQUE INDEX SQL140327115012720 ON COMPANY (ID ASC);

CREATE UNIQUE INDEX UK_4MYGV3JMS0AYTXE7BX3KFIGWG ON COMPANY (LOWERNAME ASC);

ALTER TABLE COMPANY ADD CONSTRAINT SQL140327115012720 PRIMARY KEY (ID);

