--<ScriptOptions statementTerminator=";"/>

CREATE TABLE APPUSER (
		ID VARCHAR(36) NOT NULL,
		ACCOUNTEXPIRED null DEFAULT false NOT NULL,
		ACCOUNTLOCKED null DEFAULT false NOT NULL,
		ENABLED null DEFAULT false NOT NULL,
		PASSWORD VARCHAR(50) NOT NULL,
		PASSWORDEXPIRED null DEFAULT false NOT NULL,
		ROLES VARCHAR(100) NOT NULL,
		USERNAME VARCHAR(50) NOT NULL
	);

CREATE UNIQUE INDEX SQL140312155121150 ON APPUSER (USERNAME ASC);

CREATE UNIQUE INDEX SQL140312155121080 ON APPUSER (ID ASC);

ALTER TABLE APPUSER ADD CONSTRAINT SQL140312155121080 PRIMARY KEY (ID);

